### ISSUE TITLE
 java.lang.RuntimeException: setVideoFrameRate failed

### ISSUE THREAD

**Issue by ZhuSniffsTheRose** [android/camera-samples#215] opened 2020-04-27 09:21 UTC
at android.media.MediaRecorder.setVideoFrameRate(Native Method)
        at com.example.android.camera2.video.fragments.CameraFragment.createRecorder(CameraFragment.kt:227)
        at com.example.android.camera2.video.fragments.CameraFragment.access$createRecorder(CameraFragment.kt:72)
        at com.example.android.camera2.video.fragments.CameraFragment$recorderSurface$2.invoke(CameraFragment.kt:108)
        at com.example.android.camera2.video.fragments.CameraFragment$recorderSurface$2.invoke(CameraFragment.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.example.android.camera2.video.fragments.CameraFragment.getRecorderSurface(Unknown Source:2)
        at com.example.android.camera2.video.fragments.CameraFragment.access$getRecorderSurface$p(CameraFragment.kt:72)
        at com.example.android.camera2.video.fragments.CameraFragment$initializeCamera$1.invokeSuspend(CameraFragment.kt:246)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by owahltinez** [comment] 2020-04-27 15:52
Thanks for reporting! Please answer a few questions to help us find the root cause of this issue:
* Which sample app are you using?
* Did you modify the sample app in any way?
* Can you provide concrete steps for us to reproduce this issue?
* What device and Android version are you using for testing?

**Comment by ZhuSniffsTheRose** [comment] 2020-04-28 02:40
1. Sample is  Camera2Video
2. Not modify, just clone and run Camera2Video
3.Run Camera2Video and  click any one of buttons;
4. Device Info: MIUI 10 8.11.22.  Android Version: 8.0.0

**Comment by evansgelist** [comment] 2020-04-29 08:39
same problem!
MIUI 11.0.2
8.1.0

**Comment by Sultan91** [comment] 2020-06-07 19:41
Same problem was on virtual devices <= API 25,
On nexus S API 29 works sort of ok

**Comment by owahltinez** [comment] 2020-06-09 21:33
Thank you @Sultan91, I was able to reproduce the issue on emulator. It looks like there is some precision issue with the way FPS is computed, it should be fixed now.

**Closed** 2020-06-09 21:34 UTC
