### ISSUE TITLE
CameraX Preview is cutted on Samsung S6 (G920F)

### ISSUE THREAD

**Issue by kostya29** [android/camera-samples#225] opened 2020-05-07 15:46 UTC
![samsung-g920f (S6)-preview_failed ](https://user-images.githubusercontent.com/1607263/81315387-e8962380-9092-11ea-8fab-6098ca4e5d1c.png)

**Comment by owahltinez** [comment] 2020-05-07 15:59
Thanks for reporting! Closing as duplicate of #212

**Closed by owahltinez** 2020-05-07 15:59 UTC
