### ISSUE TITLE
camera x preview and picture size not working good on samsung-m10

### ISSUE THREAD

**Issue by asifk1997** [android/camera-samples#108] opened 2019-11-24 06:42 UTC
i was using camerax-kotlin version on my samsung m10 but the previews and picture taken after snap button are not of good quality 
here is a screen shot of preview cameera x app

![Screenshot_20191124-115923_CameraX Basic](https://user-images.githubusercontent.com/16101763/69490804-8960a000-0eb2-11ea-896f-9abb5f583654.jpg)

and screenshot of preview in samsung camera app

![Screenshot_20191124-120508_Camera](https://user-images.githubusercontent.com/16101763/69490820-e52b2900-0eb2-11ea-915b-b9931bf434ba.jpg)

same is the case with pictures taken by the camera i think the problem is because of aspect ratio and screen size are not similar

here is some more info about the phone:
![Screenshot_20191124-120820_Camera2 Probe](https://user-images.githubusercontent.com/16101763/69490868-903be280-0eb3-11ea-96cd-b53b4cbf2d24.jpg)
![Screenshot_20191124-120826_Camera2 Probe](https://user-images.githubusercontent.com/16101763/69490869-903be280-0eb3-11ea-95a1-fb32697f38f1.jpg)
![Screenshot_20191124-120830_Camera2 Probe](https://user-images.githubusercontent.com/16101763/69490870-903be280-0eb3-11ea-8439-583319c41857.jpg)

**Comment by owahltinez** [comment] 2019-11-27 02:25
Thank you for reporting this! I'm 99% sure that this is a duplicate of #77. We just updated the sample to `alpha06` which should solve this issue. Please try it, and if you can still see the problem then reopen the issue :)

**Closed by owahltinez** 2019-11-27 02:25 UTC
