### ISSUE TITLE
Camera2Video - crash when double tap recording button

### ISSUE THREAD

**Issue by ecoopnet** [android/camera-samples#290] opened 2020-08-27 07:59 UTC
![v1](https://user-images.githubusercontent.com/716743/91413758-8c941c80-e886-11ea-85b0-61614794622e.gif)

```
2020-08-27 16:55:52.785 18454-19041/com.android.example.camera2.video E/MediaRecorder: output file has already been set
2020-08-27 16:55:52.789 18454-19041/com.android.example.camera2.video E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.android.example.camera2.video, PID: 18454
    java.lang.IllegalStateException
        at android.media.MediaRecorder._setOutputFile(Native Method)
        at android.media.MediaRecorder.prepare(MediaRecorder.java:1106)
        at com.example.android.camera2.video.fragments.CameraFragment$initializeCamera$1$1$1.invokeSuspend(CameraFragment.kt:274)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-08-27 16:55:53.603 18454-18454/com.android.example.camera2.video E/ActivityThread: Activity com.example.android.camera2.video.CameraActivity has leaked ServiceConnection android.media.MediaScannerConnection@f4d13d9 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.example.android.camera2.video.CameraActivity has leaked ServiceConnection android.media.MediaScannerConnection@f4d13d9 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1820)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1692)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1671)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1755)
        at android.app.ContextImpl.bindService(ContextImpl.java:1684)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
        at android.media.MediaScannerConnection.connect(MediaScannerConnection.java:162)
        at android.media.MediaScannerConnection.scanFile(MediaScannerConnection.java:313)
        at com.example.android.camera2.video.fragments.CameraFragment$initializeCamera$1$1$2.invokeSuspend(CameraFragment.kt:303)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by owahltinez** [comment] 2020-09-14 01:12
Closing as a dupe of #254

**Closed by owahltinez** 2020-09-14 01:12 UTC
