### ISSUE TITLE
Camera2BasicJava not working on emulator pixel2 and real device android pie

### ISSUE THREAD

**Issue by saadandroid** [android/camera-samples#143] opened 2020-01-08 12:37 UTC
Here is the logs:

2020-01-08 17:33:31.535 15685-15685/? I/id.camera2basi: Not late-enabling -Xcheck:jni (already on)
2020-01-08 17:33:31.595 15685-15685/? W/id.camera2basi: Unexpected CPU variant for X86 using defaults: x86
2020-01-08 17:33:34.262 15685-15685/com.example.android.camera2basic W/id.camera2basi: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
2020-01-08 17:33:34.264 15685-15685/com.example.android.camera2basic W/id.camera2basi: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
2020-01-08 17:33:34.688 15685-15696/com.example.android.camera2basic I/id.camera2basi: Background concurrent copying GC freed 8556(2MB) AllocSpace objects, 0(0B) LOS objects, 53% free, 1310KB/2MB, paused 9.951ms total 308.217ms
2020-01-08 17:33:35.703 15685-15685/com.example.android.camera2basic D/OpenGLRenderer: Skia GL Pipeline
2020-01-08 17:33:35.902 15685-15721/com.example.android.camera2basic D/HostConnection: HostConnection::get() New Host Connection established 0xe8db5230, tid 15721
2020-01-08 17:33:35.942 15685-15721/com.example.android.camera2basic D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
2020-01-08 17:33:36.075 15685-15721/com.example.android.camera2basic I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2020-01-08 17:33:36.076 15685-15721/com.example.android.camera2basic I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-01-08 17:33:36.076 15685-15721/com.example.android.camera2basic I/OpenGLRenderer: Initialized EGL, version 1.4
2020-01-08 17:33:36.076 15685-15721/com.example.android.camera2basic D/OpenGLRenderer: Swap behavior 1
2020-01-08 17:33:36.085 15685-15721/com.example.android.camera2basic D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
2020-01-08 17:33:36.085 15685-15721/com.example.android.camera2basic D/EGL_emulation: eglCreateContext: 0xe8d85540: maj 3 min 0 rcv 3
2020-01-08 17:33:36.087 15685-15721/com.example.android.camera2basic D/EGL_emulation: eglMakeCurrent: 0xe8d85540: ver 3 0 (tinfo 0xe8d83390)
2020-01-08 17:33:36.142 15685-15721/com.example.android.camera2basic D/HostConnection: createUnique: call
2020-01-08 17:33:36.142 15685-15721/com.example.android.camera2basic D/HostConnection: HostConnection::get() New Host Connection established 0xe8db5460, tid 15721
2020-01-08 17:33:36.154 15685-15721/com.example.android.camera2basic D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
2020-01-08 17:33:36.154 15685-15721/com.example.android.camera2basic E/eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
2020-01-08 17:33:36.256 15685-15721/com.example.android.camera2basic D/EGL_emulation: eglMakeCurrent: 0xe8d85540: ver 3 0 (tinfo 0xe8d83390)
2020-01-08 17:33:36.293 15685-15721/com.example.android.camera2basic D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 1 2
2020-01-08 17:33:37.651 15685-15721/com.example.android.camera2basic I/OpenGLRenderer: Davey! duration=1755ms; Flags=0, IntendedVsync=52797600919350, Vsync=52797834252674, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=52797836975040, AnimationStart=52797837216850, PerformTraversalsStart=52797837867160, DrawStart=52797925452160, SyncQueued=52797993026250, SyncStart=52798050524670, IssueDrawCommandsStart=52798053435460, SwapBuffers=52799036274570, FrameCompleted=52799413939380, DequeueBufferDuration=112000, QueueBufferDuration=548000, 
2020-01-08 17:33:37.691 15685-15685/com.example.android.camera2basic I/Choreographer: Skipped 96 frames!  The application may be doing too much work on its main thread.
2020-01-08 17:33:37.821 15685-15721/com.example.android.camera2basic I/OpenGLRenderer: Davey! duration=1733ms; Flags=0, IntendedVsync=52797837676797, Vsync=52799437676733, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=52799454633680, AnimationStart=52799454838130, PerformTraversalsStart=52799455709320, DrawStart=52799456142850, SyncQueued=52799456247950, SyncStart=52799469363310, IssueDrawCommandsStart=52799469433100, SwapBuffers=52799470366690, FrameCompleted=52799584346610, DequeueBufferDuration=104000, QueueBufferDuration=427000, 
2020-01-08 17:33:43.860 15685-15685/com.example.android.camera2basic I/CameraManagerGlobal: Connecting to camera service
2020-01-08 17:33:44.714 15685-15721/com.example.android.camera2basic I/OpenGLRenderer: Davey! duration=817ms; Flags=1, IntendedVsync=52805659744269, Vsync=52805743077599, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=52805756934680, AnimationStart=52805757057840, PerformTraversalsStart=52805757123120, DrawStart=52805892525420, SyncQueued=52805894201280, SyncStart=52805894328130, IssueDrawCommandsStart=52805894440620, SwapBuffers=52805972500100, FrameCompleted=52806477768040, DequeueBufferDuration=253000, QueueBufferDuration=1518000, 
2020-01-08 17:33:47.057 15685-15721/com.example.android.camera2basic D/EGL_emulation: eglMakeCurrent: 0xe8d85540: ver 3 0 (tinfo 0xe8d83390)
2020-01-08 17:33:47.931 15685-15685/com.example.android.camera2basic I/Choreographer: Skipped 52 frames!  The application may be doing too much work on its main thread.
2020-01-08 17:34:28.454 15685-15685/com.example.android.camera2basic W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6622657
2020-01-08 17:34:30.586 15685-15721/com.example.android.camera2basic D/EGL_emulation: eglMakeCurrent: 0xe8d85540: ver 3 0 (tinfo 0xe8d83390)
2020-01-08 17:34:31.004 15685-15685/com.example.android.camera2basic I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
2020-01-08 17:34:33.162 15685-15721/com.example.android.camera2basic D/EGL_emulation: eglMakeCurrent: 0xe8d85540: ver 3 0 (tinfo 0xe8d83390)

**Comment by owahltinez** [comment] 2020-01-17 00:31
Closing as duplicate of #82. We will probably deprecate the Camera2Basic sample soon, please refer to the Camera2Formats sample instead for now.

**Closed** 2020-01-17 00:31 UTC
