### ISSUE TITLE
Camera2BasicJava not working on pixel 2 api 28 emulator and api 28 real device 

### ISSUE THREAD

**Issue by saadandroid** [android/camera-samples#123] opened 2019-12-16 07:47 UTC
Camera2BasicJava not working on pixel 2 api 28 emulator and api 28 real device, it opens and suddenly crash app. I have not change any code just run first time

**Comment by owahltinez** [comment] 2019-12-23 16:06
Thanks for reporting, I think this is a dupe of #82. Please reopen if you think they are different issues :)

**Closed by owahltinez** 2019-12-23 16:06 UTC
